import Head from "next/head";
import Image from "next/image";
import { Fascinate_Inline, Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Box from "@mui/material/Box";
import React, { useState } from "react";
import { Typography, IconButton, Container } from "@mui/material";
import {
  useSession,
  signIn,
  signOut,
  getSession,
  UseSessionOptions,
} from "next-auth/react";
import AuthUser from "@/components/user/AuthUser";
import Guest from "@/components/user/Guest";
import { LogoutOutlined } from "@mui/icons-material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const options: UseSessionOptions<boolean> = {
    required: false,
  };

  const { data: session } = useSession(options);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* {session ? <AuthUser /> : <Guest />} */}

      <AuthUser />
    </>
  );
}
