import Head from "next/head";
import Image from "next/image";
import { Fascinate_Inline, Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Box from "@mui/material/Box";
import React, { useState } from "react";
import { Typography, Toolbar, Container } from "@mui/material";
import TabComponent from "@/components/tabs/TabComponent";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="lg">
        <Box sx={{ marginTop: { xs: "1rem", md: "4.5rem" } }}>
          <Typography
            variant="h1"
            sx={{
              color: "white",
              paddingBottom: "0.5rem",
              fontWeight: { xs: 500, md: 700 },
            }}
          >
            Main Dashboard
          </Typography>

          <TabComponent />
        </Box>
      </Container>
    </>
  );
}
